package pojos;
// Generated Nov 8, 2017 10:19:19 AM by Hibernate Tools 4.3.1



/**
 * Private generated by hbm2java
 */
public class Private  implements java.io.Serializable {


     private Integer id;
     private Users usersByRese;
     private Users usersBySender;
     private String msg;

    public Private() {
    }

	
    public Private(Users usersByRese, Users usersBySender) {
        this.usersByRese = usersByRese;
        this.usersBySender = usersBySender;
    }
    public Private(Users usersByRese, Users usersBySender, String msg) {
       this.usersByRese = usersByRese;
       this.usersBySender = usersBySender;
       this.msg = msg;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsersByRese() {
        return this.usersByRese;
    }
    
    public void setUsersByRese(Users usersByRese) {
        this.usersByRese = usersByRese;
    }
    public Users getUsersBySender() {
        return this.usersBySender;
    }
    
    public void setUsersBySender(Users usersBySender) {
        this.usersBySender = usersBySender;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }




}


